### PR TITLE
Update to .NET Core 3 Preview 9

### PR DESCRIPTION
**Pull request by kant2002**

### CODE REVIEW

**Comment by galvesribeiro** [comment]
Hello @kant2002! Thanks for the PR and sorry for the delay.

So, I'm ok with the update but, what did you replaced `Task` with `ValueTask`? In all cases (client or server-side modes) there will be an async operation on this package, so there is no point on change to it.

**Comment by kant2002** [comment]
API changed, that’s why. I have no other options.

**Comment by galvesribeiro** [comment]
OHHH!!! Sorry, I didn't saw that. Thank you! Merging.

**Pull request merged**
